config/routes.rb
Rails.application.routes.draw do
  devise_for :users 

  root to: 'welcome#index'
  resources :posts, :manuals, :shifts, :shares
  resources :welcome, only: :index
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/manual.rb
class Manual < ApplicationRecord
  has_one_attached :image
  belongs_to :user

end

app/models/post.rb
class Post < ApplicationRecord
  has_one_attached :image

  belongs_to :user

  validates  :name, :greeting, :image, presence: true
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :user

  validates  :date, :name, :explanation, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :shopname, presence: true
  has_one :post
  has_many :manuals
  has_many :shares
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!, only: [:/]

  def after_sign_in_path_for(resource)
    posts_path # ログイン後に遷移するpathを設定
  end

  def after_sign_out_path_for(resource)
    root_path # ログアウト後に遷移するpathを設定
  end

  private
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :shopname])
  end
end

app/controllers/manuals_controller.rb
class ManualsController < ApplicationController
  def index
    @manuals = Manual.all
  end

  def new
    @manual = Manual.new
  end

  def create
    @manual = Manual.new(manual_params)
    if @manual.valid?
      @manual.save
      redirect_to manuals_path
    else
      render 'new'
    end
  end

  private

  def manual_params
    params.require(:manual).permit(:title, :image, :explanation).merge(user_id: current_user.id)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.includes(:user)
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if @post.valid?
      @post.save
      redirect_to root_path
    else
      render 'new'
    end
  end
  
  private
  def post_params
    params.require(:post).permit( :name, :greeting, :image).merge(user_id: current_user.id)
  end
  # イメージをストロングパラメーターに設定
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def index
  end

  def index
    @shares = Share.all
    @share = Share.new
  end


  def create
   @share = Share.create(share_params)
    if @share.valid?
      @share.save
      redirect_to shares_path
    else
      render 'index'
    end
  end

  private
  def share_params
    params.require(:share).permit(:date, :name, :explanation).merge(user_id: current_user.id)
  end
end

app/controllers/shifts_controller.rb
class ShiftsController < ApplicationController
  def edit
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if@user.valid?
      @user.save
      redirect_to posts_path
    else
      render 'new'
    end
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/manuals_helper.rb
module ManualsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/shares_helper.rb
module SharesHelper
end

app/helpers/shifts_helper.rb
module ShiftsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>まにゅなび</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <header class="header">
      <div class="header__bar">
        <div class="grid-6"><%= link_to image_tag("rogo.png", class:"rogo"), "/" %></div>
        <% if user_signed_in? %>
          <div class="user_nav grid-6">
            <span><%= current_user.email %>
          </div>
          <% else %>
          <div class="grid-6">
            
         </div>
        <% end %>
      </div>
    </header>
    <%= yield %>
    <footer>
    </footer>
  </body>
</html>

app/views/manuals/create.html.erb
<h1>投稿が完了しました</h1>

<p><%= link_to 'マニュアル一覧に戻る',manuals_path %></P>


<p><%= link_to 'トップページに戻る', posts_path %></p>

app/views/manuals/index.html.erb
<p><div class= "top_message">マニュアル一覧</p></div>
<div class = "contents">
 <% @manuals.each do |manual| %>
    <div class="manual_post" >
      <span class ="manual_title">
        <p><%= manual.title %></p>
      </span>
      <span class ="manual_image">
        <p><%= image_tag manual.image.variant(resize:'500x500') %></p>
      </span>
      <span class="manual_explanation">
        <p><%= manual.explanation %></p>
      </span>
    </div>
  <% end %>

  <p><%= link_to 'マニュアルを追加する', new_manual_path %></p>
</div>

<p><%= link_to 'トップページに戻る', posts_path %></p>

app/views/manuals/new.html.erb
<h1>新規マニュアル登録画面</h1>

<%= form_with model: @manual, url: manuals_path, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <%= f.text_field :title, placeholder: "例）ランチの盛付け" %>
    <span class="image-file">画像</span>
    <%= f.file_field :image, class: 'hidden' %>
    <%= f.text_area :explanation, placeholder: "例）葉っぱは30g,トッピングは３種類", rows: "10" %>
    <%= f.submit '投稿する' %>
<% end %>

<p><%= link_to 'マニュアル一覧に戻る',manuals_path %></P>
<p><%= link_to 'トップページに戻る', posts_path %></p>

app/views/posts/index.html.erb
<p><div class= "top_message"><%= current_user.shopname %></div></p>
<% if @posts.present? %>
  <% @posts.each do |post| %>
      <div class="post_name" >
        <span class ="post_name">
          <p><%= post.name %></p>
        </span>
        <span class ="post_image">
          <p><%=image_tag(post.image, size:'100x100') %></p>
        </span>
        <span class="post_greeting">
          <p><%= post.greeting %></p>
        </span>
      </div>
    <% end %>
<% else %>
  <div class = "shop_greeting">
      <div class = "syacyo-image">
      <%= image_tag('shef-image.png' , size: '100x100') %>
      </div>
      <div class = "greeting">
      お店の紹介や新人さんへのメッセージをご記入ください！
      </div>
    </div>
    <%= link_to '挨拶、画像を登録する', new_post_path ,class:"post-btn"%>
<% end %>



<p><%= link_to '1.業務マニュアル ', manuals_path, class:"post_btn"  %></p>

<p><%= link_to '2.シフト確認    ', shifts_path, class:"post_btn"  %></p>

<p><%= link_to '3.引き継ぎ事項   ', shares_path, class:"post_btn" %></p>

<p><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></p>
<%# .item-red-btn {
  text-align: center;
  background-color: #ea352d;
  font-size: 24px;
  font-weight: bold;
  color: #FFF;
  margin: 20px 0px;
  padding: 2vh 10vw;これでいい感じにボタンを作ろう。
} btn のCSSも準備必要%>


<%# <span class ="manual_image">
        <p><%= image_tag manual.image.variant(resize:'500x500') %></p>
      <%# </span> %> 

app/views/posts/new.html.erb
<h1>お店の情報を入力してください</h1>

<%= form_with model: @post, url: posts_path, local: true do |f| %>
  <%= render 'shared/error_messages', model: f.object %>
    <p>代表者氏名</p>
    <%= f.text_field :name, placeholder: "例）大谷　美子" %>
    <p><span class="image-file">代表者画像</span></p>
    <%= f.file_field :image, class: 'hidden' %>
    <p>代表者よりメッセージ</p>
    <%= f.text_area :greeting, placeholder: "例）新人さんへのメッセージを・・・！", rows: "10" %>
    <%= f.submit '投稿する' %>
<% end %>

<p><%= link_to 'トップページに戻る', posts_path %></p>

app/views/shared/_error_messages.html.erb
<% if model.errors.any? %>
<div class="error-alert">
  <ul>
    <% model.errors.full_messages.each do |message| %>
    <li class='error-message'><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shares/index.html.erb
<p><div class= "top_message">引き継ぎ事項</p></div>
<% @shares.each do |share| %>
    <div class="share_post" >
      <span class ="share_date">
        <p><%= share.date %></p>
      </span>
      <span class ="share_name">
        <p><%= share.name %></p>
      </span>
      <span class="share_explanation">
        <p><%= share.explanation %></p>
      </span>
    </div>
  <% end %>

<p><div class ="share_comment">
  <%= form_with model: @share, url: shares_path, local: true do |f| %>
    <div class = "share_date" ><%= f.text_field :date, placeholder: "例）2023/3/4" %></div>
    <div class = "share_name" ><%= f.text_field :name, placeholder: "例）吉田" %></div>
    <div class = "share_explanation" > <%= f.text_area :explanation, placeholder: "例）田中さんきましたよ！新メニューお気に入りのようです！", rows: "10" %></div>
    <p><div class = "btn" ><%= f.submit '投稿する' %></div></p>
  <% end %>
</div></p>

<p><%= link_to 'トップページに戻る', posts_path %></p>

app/views/shifts/index.html.erb
<h1>シフト確認</h1>
<div class ="caution">
<p>シフト締め切りは毎月２０日です！</p>
<p>シフト作るの大変なので期日は厳守でお願いします！</P>
</div>
<div class= "googlecalender">
<iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;ctz=Asia%2FTokyo&amp;src=a2FkYWlzZW5ueW91YWthdW50bzA5MjFAZ21haWwuY29t&amp;src=YWRkcmVzc2Jvb2sjY29udGFjdHNAZ3JvdXAudi5jYWxlbmRhci5nb29nbGUuY29t&amp;src=amEuamFwYW5lc2UjaG9saWRheUBncm91cC52LmNhbGVuZGFyLmdvb2dsZS5jb20&amp;color=%23039BE5&amp;color=%2333B679&amp;color=%230B8043&amp;showTitle=0" style="border:solid 1px #777" width="800" height="600" frameborder="0" scrolling="no"></iframe>
</div>

<p><%= link_to 'トップページに戻る', posts_path %></p>

app/views/users/edit.html.erb
<div class='account-page' id='account-page'>
  <div class='account-page__inner clearfix'>
    <div class='account-page__inner--left account-page__header'>
      <h2>Edit Account</h2>
      <h5>アカウントの編集</h5>
      <%= link_to "ログアウト", "#", class: 'btn'%>
      <%= link_to "チャットページに戻る", :back, class: 'btn'%>
    </div>
    <div class='account-page__inner--right user-form'>
      <%= form_with model: current_user, local: true do |f|%>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :name%>
          </div>
          <div class='field-input'>
            <%= f.text_field :name, autofocus: true%>
          </div>
        </div>
        <div class='field'>
          <div class='field-label'>
            <%= f.label :email%>
          </div>
          <div class='field-input'>
            <%= f.email_field :email%>
          </div>
        </div>
        <div class='actions'>
          <%= f.submit "Update", class: 'btn'%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<p><div class= "top_message">Welcome to まにゅなび</p></div>
<p><span class = "sign-in">
<%= link_to '会員様はこちら', new_user_session_path,class:"post-btn"%>
</span></p>

<p><span class = "sign-up">
<%= link_to '新規登録の方はこちら', new_user_registration_path ,class:"post-btn"%>
</span></p>

<%# ★post-btnにCSS設定が必要 %>